### ISSUE TITLE
StarTech S355BU33ERM and S358BU33ERM compatible

### ISSUE THREAD

**Issue by dajhorn** [projectgus/jms567ctl#1]
I used jms567ctl to unbrick a StarTech S358BU33ERM external disk enclosure and reinstall the vendor 00.03.01.10 firmware.

* https://www.startech.com/en-us/hdd/s358bu33erm
* ![S358BU33ERM](https://github.com/projectgus/jms567ctl/assets/494022/d98b08fe-91a3-4683-ab68-82d5cebc472d)

This utility is very likely compatible with the StarTech S355BU33ERM because it uses the same firmware image:

* https://www.startech.com/en-us/hdd/s355bu33erm
* ![S355BU33ERM](https://github.com/projectgus/jms567ctl/assets/494022/d446ec63-7cbd-40b1-b5bb-efb7f803097d)

Thanks for publishing this tool.

**Comment by projectgus** [comment]
Thanks @dajhorn! I've added a list of "has worked with" devices to the README.
